//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mysalecity.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class user_statuses
    {
        public long id { get; set; }
        public string user_status { get; set; }
    }
}
